name: CI

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]
        platform:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64

    steps:
      - name: Set up Go ${{ matrix.version.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build
        env:
          GOOS: ${{ matrix.platform.os }}
          GOARCH: ${{ matrix.platform }}
        run: |
          go build -o onewire-exporter-${{ matrix.platform.os }}-${{ matrix.platform.arch }} -v ./...

      #- name: Test
      #  env:
      #    GOOS: ${{ matrix.platform.os }}
      #    GOARCH: ${{ matrix.platform.arch }}
      #  run: |
      #    go test -v ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: onewire-exporter-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          path: onewire-exporter-${{ matrix.platform.os }}-${{ matrix.platform.arch }}